pipelines:
  nginx-deploy:
    group: WebServers
    materials:
      - git:
          url: https://github.com/your-repo/nginx-deploy.git
          branch: main
    stages:
      - Build:
          jobs:
            - BuildImage:
                tasks:
                  - exec:
                      command: docker
                      arguments: ["build", "-t", "nginx-website", "."]
                  - exec:
                      command: docker
                      arguments: ["run", "--rm", "nginx-website", "nginx", "-t"]
      - Deploy:
          jobs:
            - DeployToServer:
                tasks:
                  - exec:
                      command: docker
                      arguments: ["run", "-d", "-p", "80:80", "--name", "nginx-container", "nginx-website"]
                  - exec:
                      command: docker
                      arguments: ["exec", "nginx-container", "nginx", "-s", "reload"]
                  - exec:
                      command: echo
                      arguments: ["Website successfully deployed on Nginx"]

# Simple Website Content Example
directory_structure:
  html/:
    - index.html
    - styles.css
    - script.js

# Example HTML content: index.html
html_content: |
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Simple Website</title>
      <link rel="stylesheet" href="styles.css">
  </head>
  <body>
      <h1>Welcome to My Simple Website</h1>
      <p>This is a basic Nginx-hosted website.</p>
      <script src="script.js"></script>
  </body>
  </html>

# Example CSS content: styles.css
css_content: |
  body {
      font-family: Arial, sans-serif;
      text-align: center;
      margin-top: 50px;
  }

# Example JavaScript content: script.js
js_content: |
  console.log("Website is running!");
